services:
  webpage:
    build: ./professional/
    ports:
      - "5005:5005"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://webpage:5005"]
      interval: 5s
      timeout: 1s
      retries: 3

  mongodb:
    image: mongo:8.0.6
    volumes:
      - type: bind
        # ToDo: fix: hardcode for omniserv deploy: ~/omni/omniscient/data
        source: ${DATA_DIR} # am I autistic wtf
        target: /data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USR}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
    ports:
      - "27017:27017" # Leave ports for manual intervention

  omniscient:
    build: ./omniscient/
    environment:
      - MONGO_USR=${MONGO_USR}
      - MONGO_PWD=${MONGO_PWD}
    ports:
      - "5003:5003"
    depends_on:
      mongodb:
        restart: true
        condition: service_started

  api:
    build: ./api/
    environment:
      - API_SECRET=$API_SECRET
    ports:
      - "5006:5006"
    depends_on:
      omniscient:
        restart: true
        condition: service_started
      smartlife:
        restart: true
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:5006/health"]
      interval: 5s
      timeout: 1s
      retries: 3

  smartlife:
    build: ./smartlife/
    environment:
      - STRIP_IP=$STRIP_IP
      - CITY=$CITY
      - PROD=$PROD
    ports:
      - "5002:5002"

